export const GET_GENRE_SONGS_LOADING = 'GET_GENRE_SONGS_LOADING';
export const GET_GENRE_SONGS_SUCCESS = 'GET_GENRE_SONGS_SUCCESS';
export const GET_GENRE_SONGS_ERROR = 'GET_GENRE_SONGS_ERROR';

export const GET_ARTIST_SONGS_LOADING = 'GET_ARTIST_SONGS_LOADING';
export const GET_ARTIST_SONGS_SUCCESS = 'GET_ARTIST_SONGS_SUCCESS';
export const GET_ARTIST_SONGS_ERROR = 'GET_ARTIST_SONGS_ERROR';

export const GET_LANGUAGE_SONGS_LOADING = 'GET_LANGUAGE_SONGS_LOADING';
export const GET_LANGUAGE_SONGS_SUCCESS = 'GET_LANGUAGE_SONGS_SUCCESS';
export const GET_LANGUAGE_SONGS_ERROR = 'GET_LANGUAGE_SONGS_ERROR';
