export const UPDATE_CURRENT_PLAYLIST = 'UPDATE_CURRENT_PLAYLIST';
export const PLAY_SONG = 'PLAY_SONG';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const TOGGLE_WIDGET = 'TOGGLE_WIDGET';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
